# Data-driven analysis using diffcyt to reveal immune phenotype that distinguish MS-affected from unaffected twin pairs
# as presented in Ingelfinger, Gerdes et al. "Twin study reveals non-heritable immune perturbations in multiple sclerosis"

# load library
library(gdata)
library(dplyr)
library(plyr)
library(reshape2)
library(Cairo)
library(diffcyt)
library(HDCytoData)
library(CATALYST)

# read data and merge with meta data
setwd("/Immunology_shares/Becherlab/People/Ingelfinger/DATA/Multiple Sclerosis/Twin Study/Pooled runs/Surface/1_tsne_flowSOM_main/")

load(file="data_main_clust_k6.RDa")
data <- data_clustered[,c(1:39, 41)]
md <- read.xls("../../meta_twins.xlsx")

data_md <- merge(data, md, by = "sample_id")

# Filter dataframe for monozygotic twin pairs that met the inclusion criteria
# note: this excludes twin pairs for which either 1) a clinical definitive MS was not diagnosed in the MS twin, 2) the non-MS twin was diagnosed with a clinically isolated syndrom or
# 3) dizygotic twin pairs
inclusion <- subset(md, disease_state=="Multiple Sclerosis" & inclusion ==1)
inclusion_pairs <- unique(inclusion$pair)
data_md_inclusion <- subset(data_md, pair %in% inclusion_pairs)

# exclude twin pairs for which only data for one twin was available
inc_pair_table <- table(data_md_inclusion$pair, data_md_inclusion$disease_state)
inc_pair.df <- data.frame(inc_pair_table)
inc_valid.pairs <- subset(data.frame(table(subset(inc_pair.df, Freq != 0)[,1])), Freq ==2)[,1]
data_inc.val <- subset(data_md, pair %in% inc_valid.pairs)

# convert dataframe in list for each sample
data_inc.val.m <- data.matrix(data_inc.val)
data_list_inc <- split(data_inc.val, f = data_inc.val$sample_id)
data_list_inc.m <- lapply(data_list_inc, data.matrix)

# setup experiment and marker info for diffcyt
md_inc.val <- subset(md, pair %in% inc_valid.pairs)
md_inc.val  <- md_inc.val[ order(match(md_inc.val$sample_id, unique(data_inc.val.m[,"sample_id"]))), ]
sample_id <- md_inc.val$sample_id
group_id <- factor(md_inc.val$disease_state, levels= c("Multiple Sclerosis", "Healthy"))
patient_id <- factor(md_inc.val$pair, levels= unique(md_inc.val$pair))
experiment_info <- data.frame(group_id, patient_id, sample_id, stringsAsFactors = FALSE)

# column indices of all markers, lineage markers, and functional markers
cols_markers <- c(3:34, 36:38)
cols_lineage <- c(3, 4, 5, 7, 9, 11, 12, 13, 19, 20, 21, 24, 25, 26, 27, 29, 31, 32, 36, 37, 38)
cols_func <- setdiff(cols_markers, cols_lineage)

# channel and marker names
channel_name <- colnames(data_inc.val)
marker_name <- channel_name

# define marker classes
# note: using lineage markers for 'cell type', and functional markers for 'cell state'
marker_class <- rep("none", ncol(data_inc.val))
marker_class[cols_lineage] <- "type"
marker_class[cols_func] <- "state"
marker_class <- factor(marker_class, levels = c("type", "state", "none"))

marker_info <- data.frame(
  channel_name, marker_name, marker_class, stringsAsFactors = FALSE
)

# create design and contrast matrix
design <- createDesignMatrix(
  experiment_info, cols_design = c("group_id", "patient_id")
)

contrast <- createContrast(c(0, 1, rep(0, (ncol(design)-2))))
nrow(contrast) == ncol(design)

# run diffcyt analysis for DS; note: at this step we just retrieve the clustering column and run the DS model again for 
# both subsets: 1) all twin pairs, 2) untreated twin pairs in order to find features that are significant for both conditions
out_DS <- diffcyt(
  d_input = data_list_inc.m, 
  experiment_info = experiment_info, 
  marker_info = marker_info, 
  design = design, 
  contrast = contrast, 
  analysis_type = "DS", 
  seed_clustering = 123, 
  plot = FALSE,
  transform=F
)

# export automated high resolution FlowSOM clusters generated by the diffcyt wrapper function
data_incl_clust <- cbind(data_inc.val.m, data.frame(rowData(out_DS$d_se)))
save(data_incl_clust, file="2019-12-16_DS_clustered_full.RDa")

# subset on untreated twin pairs and repeat
untreated <- subset(md, disease_state=="Multiple Sclerosis" & DMT=="" & inclusion ==1)
untreated_pairs <- unique(untreated$pair)
data_md_untreated <- subset(data_md, pair %in% untreated_pairs)

pair_table <- table(data_md_untreated$pair, data_md_untreated$disease_state)
pair.df <- data.frame(pair_table)
valid.pairs <- subset(data.frame(table(subset(pair.df, Freq != 0)[,1])), Freq ==2)[,1]
data_unt.val  <- subset(data_inc.val, pair %in% valid.pairs)
data_list_unt <- split(data_unt.val, f = data_unt.val$sample_id)
data_list_unt.m <- lapply(data_list_unt, data.matrix)

# setup of experiment and marker info for untreated twin pairs
md_unt.val <- subset(md, pair %in% valid.pairs)
md_unt.val  <- md_unt.val[ order(match(md_unt.val$sample_id, unique(data_unt.val[,"sample_id"]))), ]

sample_id <- md_unt.val$sample_id
group_id <- factor(md_unt.val$disease_state, levels= c("Multiple Sclerosis", "Healthy"))
patient_id_unt <- factor(md_unt.val$pair, levels= unique(md_unt.val$pair))
experiment_info_unt <- data.frame(group_id, patient_id_unt, sample_id, stringsAsFactors = FALSE)


# create design and contrast matrix for untreated twin pairs
design_unt <- createDesignMatrix(
  experiment_info_unt, cols_design = c("group_id", "patient_id_unt")
)

contrast_unt <- createContrast(c(0, 1, rep(0, (ncol(design_unt)-2))))
nrow(contrast_unt) == ncol(design_unt)

# Prepare data
d_se <- prepareData(data_list_inc.m, experiment_info, marker_info)
d_se.clust  <- d_se

d_se_unt <- prepareData(data_list_unt.m, experiment_info_unt, marker_info)
d_se.unt_clust  <- d_se_unt

# transfer cluster labels
rowData(d_se.clust)[, "cluster_id"]  <- data_incl_clust[,"cluster_id"]
data_unt_clust  <- subset(data_incl_clust, sample_id %in% md_unt.val$sample_id)
rowData(d_se.unt_clust)[, "cluster_id"]  <- data_unt_clust[,"cluster_id"]

# generate counts and medians for the DS limma model
d_counts <- calcCounts(d_se.clust)
d_medians <- calcMedians(d_se.clust)

d_counts_unt <- calcCounts(d_se.unt_clust)
d_medians_unt <- calcMedians(d_se.unt_clust)

# run DS limma
res_DS_incl <- testDS_limma(d_counts, d_medians, design, contrast, plot = FALSE)
res.df_incl  <- topTable(res_DS_incl, format_vals = FALSE, all= TRUE) %>% data.frame

res_DS_unt <- testDS_limma(d_counts_unt, d_medians_unt, design_unt, contrast_unt, plot = FALSE)
res.df_unt  <- topTable(res_DS_unt, format_vals = TRUE, all= TRUE) %>% data.frame

# compare hits and retrieve features that meet both conditions
res.df_unt_sub  <- subset(res.df_unt, p_adj < 0.05)
res.df_unt_sub$int.clust.ant  <- interaction(res.df_unt_sub$cluster_id, res.df_unt_sub$marker_id)

res.df_int_sub  <- subset(res.df_incl, p_adj < 0.05)
res.df_int_sub$int.clust.ant  <- interaction(res.df_int_sub$cluster_id, res.df_int_sub$marker_id)

res_common  <- res.df_unt_sub[res.df_unt_sub$int.clust.ant %in% res.df_int_sub$int.clust.ant,]
colnames(res_common)[3:4]  <- paste(colnames(res_common)[3:4], "unt", sep ="_")

res_common_comb  <- merge(res_common, res.df_int_sub[,3:5])
colnames(res_common_comb)[6:7]  <- paste(colnames(res_common_comb)[6:7], "inc", sep ="_")

# export stats
write.csv(res_common_comb, file = "2021-08-30_DS_model/common_results.csv")